import { useEffect, useRef, lazy, Suspense } from 'react';
import { Routes, Route, useLocation, useNavigate, useNavigationType } from 'react-router-dom';
import { motion, AnimatePresence } from 'framer-motion';
import Layout from './layouts/Layout';
import Home from './pages/Home';
const Outreaches = lazy(() => import('./pages/Outreaches'));
const Events = lazy(() => import('./pages/Events'));
const Checkin = lazy(() => import('./pages/Checkin'));
const Give = lazy(() => import('./pages/Give'));
const Connect = lazy(() => import('./pages/Connect'));
const Live = lazy(() => import('./pages/Live'));
const Meetings = lazy(() => import('./pages/Meetings'));
const LeaderVideoAdmin = lazy(() => import('./pages/LeaderVideoAdmin'));
const Sermons = lazy(() => import('./pages/Sermons'));
const ServiceVenues = lazy(() => import('./pages/ServiceVenues'));
const Auth = lazy(() => import('./pages/Auth'));
const ForgotPassword = lazy(() => import('./pages/ForgotPassword'));
const ResetPassword = lazy(() => import('./pages/ResetPassword'));
const Dashboard = lazy(() => import('./pages/Dashboard'));
const RecordSouls = lazy(() => import('./pages/RecordSouls'));
const LeadersForumWithFellowship = lazy(() => import('./pages/LeadersForumWithFellowship'));
const FellowshipLocationsAdminSecure = lazy(() => import('./pages/FellowshipLocationsAdminSecure'));
const NotificationCenter = lazy(() => import('./pages/NotificationCenter'));
const Notifications = lazy(() => import('./pages/Notifications'));
const ContentAdminPanel = lazy(() => import('./pages/ContentAdminPanel'));
import { useAuth } from './context/AuthContext'; import OfflineBanner from './components/OfflineBanner'; import NotificationPermissionPrompt from './components/NotificationPermissionPrompt'; import UpdateAvailablePrompt from './components/UpdateAvailablePrompt'; import { startOfflineSyncListeners } from './offlineSync';
import ErrorBoundary from './components/ErrorBoundary';
const RouteFallback = () => <div className="grid min-h-[60vh] place-items-center"><div className="h-8 w-8 animate-spin rounded-full border-2 border-white/15 border-t-gold-500" aria-label="Loading" role="status" /></div>;
const FellowshipLocationsPage = () => { const navigate = useNavigate(); return <div className="relative"><div className="mx-auto max-w-7xl px-4 pt-6 sm:px-6 lg:px-8"><button type="button" onClick={() => navigate('/leaders-forum')} className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/[0.04] px-4 py-2 text-sm font-semibold text-white/75">← Back to Leaders Forum</button></div><FellowshipLocationsAdminSecure /></div>; };
const AdminContentPage = () => { const navigate = useNavigate(); return <div className="relative"><div className="mx-auto max-w-7xl px-4 pt-6 sm:px-6 lg:px-8"><button type="button" onClick={() => navigate('/leaders-forum')} className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/[0.04] px-4 py-2 text-sm font-semibold text-white/75">← Back to Leaders Forum</button></div><ContentAdminPanel /></div>; };
const BOTTOM_TAB_PATHS = ['/', '/events', '/checkin', '/live'];
const notificationDestination = (notification) => { const data = notification?.data || notification?.extra || {}; const type = typeof data.type === 'string' ? data.type : 'announcement'; const id = typeof data.id === 'string' ? data.id.trim() : ''; if (type === 'event') return `/events${id ? `?notificationId=${encodeURIComponent(id)}` : ''}`; if (type === 'sermon') return `/sermons${id ? `?notificationId=${encodeURIComponent(id)}` : ''}`; if (type === 'outreach') return `/outreaches${id ? `?notificationId=${encodeURIComponent(id)}` : ''}`; if (type === 'venue') return `/venues${id ? `?chapter=${encodeURIComponent(id)}` : ''}`; return '/notifications'; };
const AnimatedRoutes = () => { const location = useLocation(); const navigationType = useNavigationType(); const { user } = useAuth(); const route = (element) => <Layout>{element}</Layout>; const prevPathRef = useRef(location.pathname); useEffect(() => { window.scrollTo({ top: 0, left: 0, behavior: 'auto' }); }, [location.pathname]); const isTabSwitch = BOTTOM_TAB_PATHS.includes(location.pathname) && BOTTOM_TAB_PATHS.includes(prevPathRef.current) && location.pathname !== prevPathRef.current; const transition = isTabSwitch ? { initial: { opacity: 0 }, animate: { opacity: 1 }, exit: { opacity: 0 }, duration: 0.15 } : navigationType === 'POP' ? { initial: { opacity: 0, x: -24 }, animate: { opacity: 1, x: 0 }, exit: { opacity: 0, x: 24 }, duration: 0.28 } : { initial: { opacity: 0, x: 24 }, animate: { opacity: 1, x: 0 }, exit: { opacity: 0, x: -24 }, duration: 0.28 }; useEffect(() => { prevPathRef.current = location.pathname; }); return <AnimatePresence mode="wait"><motion.div key={location.pathname} initial={transition.initial} animate={transition.animate} exit={transition.exit} transition={{ duration: transition.duration }}><ErrorBoundary key={location.pathname}><Suspense fallback={<RouteFallback />}><Routes location={location}>
<Route path="/" element={route(<Home />)} /><Route path="/outreaches" element={route(<Outreaches />)} /><Route path="/events" element={route(<Events />)} /><Route path="/live" element={route(<Live />)} /><Route path="/meetings" element={route(<Meetings />)} /><Route path="/leader-admin/video" element={route(<LeaderVideoAdmin />)} /><Route path="/sermons" element={route(<Sermons />)} /><Route path="/venues" element={route(<ServiceVenues />)} /><Route path="/checkin" element={route(<Checkin />)} /><Route path="/give" element={route(<Give />)} /><Route path="/connect" element={route(<Connect />)} /><Route path="/auth" element={route(<Auth />)} /><Route path="/forgot-password" element={route(<ForgotPassword />)} /><Route path="/reset-password" element={route(<ResetPassword />)} /><Route path="/dashboard" element={route(user ? <Dashboard /> : <Auth />)} /><Route path="/record-souls" element={route(user ? <RecordSouls /> : <Auth />)} /><Route path="/leaders-forum" element={route(<LeadersForumWithFellowship />)} /><Route path="/fellowship-locations" element={route(<FellowshipLocationsPage />)} /><Route path="/leaders-forum/notifications" element={route(<NotificationCenter />)} /><Route path="/notifications" element={route(<Notifications />)} /><Route path="/admin" element={route(<AdminContentPage />)} /><Route path="*" element={route(<Home />)} />
</Routes></Suspense></ErrorBoundary></motion.div></AnimatePresence>; };
function App() { const navigate = useNavigate(); useEffect(() => startOfflineSyncListeners(), []); useEffect(() => { let mounted = true; let pushListener; let localListener; (async () => { if (!mounted) return; try { const { PushNotifications } = await import('@capacitor/push-notifications'); pushListener = await PushNotifications.addListener('pushNotificationActionPerformed', ({ notification }) => navigate(notificationDestination(notification))); } catch {} try { const { LocalNotifications } = await import('@capacitor/local-notifications'); localListener = await LocalNotifications.addListener('localNotificationActionPerformed', ({ notification }) => navigate(notificationDestination(notification))); } catch {} })(); return () => { mounted = false; pushListener?.remove?.(); localListener?.remove?.(); }; }, [navigate]); useEffect(() => { const body = document.body, html = document.documentElement; const previousBodyOverflow = body.style.overflow, previousBodyTouchAction = body.style.touchAction; const previousHtmlOverflow = html.style.overflow, previousHtmlTouchAction = html.style.touchAction; const isFullScreenOverlay = (el) => { if (!(el instanceof HTMLElement) || !el.classList.contains('fixed')) return false; const className = String(el.className); const fillsViewport = el.classList.contains('inset-0') || (el.classList.contains('top-0') && el.classList.contains('bottom-0')); if (!fillsViewport) return false; const text = el.textContent || ''; return className.includes('z-[') || /(?:^|:)z-(?:40|50|\[\d+\])/.test(className) || /backdrop|modal|overlay|dialog|Leaders tool|Leadership Tools|Member Check-In|Check Attendance|Manage (?:Events|Outreach Stories|Sermons|Service Venues|Live Stream)/i.test(text) || el.hasAttribute('data-live-welcome-overlay') || el.getAttribute('role') === 'dialog' || el.hasAttribute('data-leadership-tools-overlay'); }; const syncBodyScrollLock = () => { const locked = Array.from(document.querySelectorAll('.fixed')).some(isFullScreenOverlay); body.style.overflow = locked ? 'hidden' : previousBodyOverflow; body.style.touchAction = locked ? 'none' : previousBodyTouchAction; html.style.overflow = locked ? 'hidden' : previousHtmlOverflow; html.style.touchAction = locked ? 'none' : previousHtmlTouchAction; }; syncBodyScrollLock(); const observer = new MutationObserver(syncBodyScrollLock); observer.observe(document.body, { childList: true, subtree: true, attributes: true, attributeFilter: ['class', 'style', 'role', 'data-leadership-tools-overlay', 'data-live-welcome-overlay'] }); return () => { observer.disconnect(); body.style.overflow = previousBodyOverflow; body.style.touchAction = previousBodyTouchAction; html.style.overflow = previousHtmlOverflow; html.style.touchAction = previousHtmlTouchAction; }; }, []); return <><OfflineBanner /><AnimatedRoutes /><NotificationPermissionPrompt /><UpdateAvailablePrompt /></>; }
export default App;
