import { useEffect, useState } from 'react';
import { FiBookmark, FiHeart, FiMessageCircle, FiArrowRight } from 'react-icons/fi';
import { useNavigate } from 'react-router-dom';
import { fetchSavedFeed, toggleSave } from '../utils/feed';
import { useAuth } from '../context/AuthContext';

export default function Bookmarks() {
  const { user } = useAuth();
  const navigate = useNavigate();
  const [posts, setPosts] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const load = async () => { setLoading(true); setError(''); try { const result = await fetchSavedFeed({ limit: 50 }); setPosts(result.posts || []); } catch (err) { setError(err?.message || 'Unable to load your bookmarks.'); } finally { setLoading(false); } };
  useEffect(() => { if (user) load(); else setLoading(false); }, [user]);
  const remove = async (id) => { try { await toggleSave(id); setPosts((current) => current.filter((post) => post.id !== id)); } catch (err) { setError(err?.message || 'Unable to remove bookmark.'); } };
  if (!user) return <main className="grid min-h-[70vh] place-items-center bg-[#0B0F14] px-6 text-center text-white"><div><FiBookmark className="mx-auto h-10 w-10 text-[#3B82F6]" /><h1 className="mt-4 text-xl font-bold">Sign in to see your bookmarks</h1><p className="mt-2 text-sm text-white/40">Save posts and come back to them anytime.</p><button onClick={() => navigate('/auth')} className="mt-5 rounded-xl bg-[#3B82F6] px-5 py-2.5 text-sm font-semibold shadow-sm hover:bg-[#2563EB]">Sign in</button></div></main>;
  return <main className="min-h-screen bg-[#0B0F14] pb-28 text-white"><div className="mx-auto max-w-3xl px-4 py-6 sm:px-6 sm:py-8"><header className="border-b border-white/[.07] pb-5"><p className="text-[11px] font-bold uppercase tracking-[.2em] text-[#3B82F6]">Your collection</p><h1 className="mt-1 text-2xl font-extrabold">Bookmarks</h1><p className="mt-2 text-sm text-white/40">Posts you saved for later.</p></header>
    {error && <div className="mt-4 rounded-2xl border border-red-400/20 bg-red-400/10 p-4 text-sm text-red-200">{error}</div>}
    {loading ? <div className="mt-5 space-y-3">{[1,2,3].map((i) => <div key={i} className="h-36 animate-pulse rounded-3xl bg-white/[.04]" />)}</div> : posts.length ? <div className="mt-5 space-y-3">{posts.map((post) => <article key={post.id} className="rounded-3xl border border-white/[.07] bg-white/[.025] p-5"><div className="flex items-start gap-3"><div className="min-w-0 flex-1"><p className="text-sm font-bold">{post.author}</p><p className="mt-1 text-xs text-white/30">{post.time || 'Saved post'}</p></div><button onClick={() => remove(post.id)} aria-label="Remove bookmark" className="rounded-xl p-2 text-[#3B82F6] hover:bg-white/[.06]"><FiBookmark className="h-4 w-4 fill-current" /></button></div>{post.title && <h2 className="mt-4 text-base font-bold">{post.title}</h2>}<p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-white/70">{post.body || 'Saved media'}</p>{post.mediaUrl && <img src={post.mediaUrl} alt="" className="mt-4 max-h-80 w-full rounded-2xl object-cover" />}<div className="mt-4 flex items-center gap-5 text-xs text-white/35"><span className="inline-flex items-center gap-1"><FiHeart /> {post.likeCount || 0}</span><span className="inline-flex items-center gap-1"><FiMessageCircle /> {post.commentCount || 0}</span><button onClick={() => navigate('/feed?notificationId=' + encodeURIComponent(post.id))} className="ml-auto inline-flex items-center gap-1 font-semibold text-white/55 hover:text-white">Open <FiArrowRight /></button></div></article>)}</div> : <div className="mt-12 rounded-3xl border border-dashed border-white/10 px-6 py-16 text-center"><FiBookmark className="mx-auto h-8 w-8 text-white/20" /><p className="mt-4 font-semibold text-white/65">Nothing saved yet</p><p className="mt-1 text-sm text-white/35">Tap the bookmark on any Feed post to save it here.</p><button onClick={() => navigate('/feed')} className="mt-5 rounded-xl bg-white px-5 py-2.5 text-xs font-semibold text-[#0B0F14] hover:bg-white/90">Explore Feed</button></div>}</div></main>;
}