create table if not exists public.feed_post_views (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.feed_posts(id) on delete cascade,
  user_email text not null,
  created_at timestamptz not null default now(),
  unique (post_id, user_email)
);

create index if not exists feed_post_views_post_id_idx on public.feed_post_views(post_id);
create index if not exists feed_post_views_user_email_idx on public.feed_post_views(lower(user_email));

alter table public.feed_post_views enable row level security;

comment on table public.feed_post_views is 'Server-managed unique Feed post views. Accessed through the authenticated Cloudflare Worker API.';
