create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  recipient_email text not null,
  actor_email text,
  type text not null check (type in ('like','reply','follow','mention','repost','quote')),
  post_id text,
  body text not null default '',
  created_at timestamptz not null default now(),
  read_at timestamptz
);

create index if not exists notifications_recipient_created_idx
  on public.notifications(lower(recipient_email), created_at desc, id desc);
create index if not exists notifications_unread_idx
  on public.notifications(lower(recipient_email), read_at, created_at desc);
alter table public.notifications enable row level security;

create or replace function public.create_feed_notification()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  recipient text;
  actor text;
  target_post text;
  notification_type text;
begin
  actor := lower(coalesce(new.user_email, ''));
  recipient := '';
  target_post := null;
  notification_type := null;

  if TG_TABLE_NAME = 'feed_user_follows' then
    recipient := lower(coalesce(new.followed_email, ''));
    notification_type := 'follow';
  elsif TG_TABLE_NAME = 'feed_post_likes' then
    select lower(p.user_email), 'p:' || p.id::text into recipient, target_post
      from public.feed_posts p where p.id = new.post_id;
    notification_type := 'like';
  elsif TG_TABLE_NAME = 'feed_post_comments' then
    select lower(p.user_email), 'p:' || p.id::text into recipient, target_post
      from public.feed_posts p where p.id = new.post_id;
    notification_type := 'reply';
  else
    return new;
  end if;

  if recipient = '' or actor = '' or recipient = actor then return new; end if;

  insert into public.notifications(recipient_email, actor_email, type, post_id, body)
  values (
    recipient,
    actor,
    notification_type,
    target_post,
    case when notification_type = 'reply' then left(coalesce(new.body, ''), 500) else '' end
  );
  return new;
end;
$$;

drop trigger if exists feed_follow_notification_trigger on public.feed_user_follows;
create trigger feed_follow_notification_trigger after insert on public.feed_user_follows
for each row execute function public.create_feed_notification();

drop trigger if exists feed_post_like_notification_trigger on public.feed_post_likes;
create trigger feed_post_like_notification_trigger after insert on public.feed_post_likes
for each row execute function public.create_feed_notification();

drop trigger if exists feed_post_comment_notification_trigger on public.feed_post_comments;
create trigger feed_post_comment_notification_trigger after insert on public.feed_post_comments
for each row execute function public.create_feed_notification();

revoke all on function public.create_feed_notification() from public;
