create table if not exists public.feed_likes (
  id bigint generated by default as identity primary key,
  sermon_id integer not null references public.sermons(id) on delete cascade,
  user_email text not null,
  created_at timestamptz not null default now(),
  unique (sermon_id, user_email)
);

create index if not exists feed_likes_sermon_id_idx on public.feed_likes(sermon_id);
create index if not exists feed_likes_user_email_idx on public.feed_likes(lower(user_email));

create table if not exists public.feed_saves (
  id bigint generated by default as identity primary key,
  sermon_id integer not null references public.sermons(id) on delete cascade,
  user_email text not null,
  created_at timestamptz not null default now(),
  unique (sermon_id, user_email)
);

create index if not exists feed_saves_sermon_id_idx on public.feed_saves(sermon_id);
create index if not exists feed_saves_user_email_idx on public.feed_saves(lower(user_email));

create table if not exists public.feed_comments (
  id bigint generated by default as identity primary key,
  sermon_id integer not null references public.sermons(id) on delete cascade,
  user_email text not null,
  author_name text not null,
  body text not null check (char_length(body) between 1 and 1000),
  created_at timestamptz not null default now()
);

create index if not exists feed_comments_sermon_id_created_at_idx on public.feed_comments(sermon_id, created_at desc);
create index if not exists feed_comments_user_email_idx on public.feed_comments(lower(user_email));

alter table public.feed_likes enable row level security;
alter table public.feed_saves enable row level security;
alter table public.feed_comments enable row level security;

comment on table public.feed_likes is 'Server-managed Feed likes. Accessed through the authenticated Cloudflare Worker API.';
comment on table public.feed_saves is 'Server-managed Feed saves. Accessed through the authenticated Cloudflare Worker API.';
comment on table public.feed_comments is 'Server-managed Feed comments. Accessed through the authenticated Cloudflare Worker API.';
