create table if not exists public.feed_user_follows (
  id bigint generated by default as identity primary key,
  follower_email text not null,
  followed_email text not null,
  created_at timestamptz not null default now(),
  check (lower(follower_email) <> lower(followed_email))
);

create unique index if not exists feed_user_follows_pair_idx
  on public.feed_user_follows (lower(follower_email), lower(followed_email));
create index if not exists feed_user_follows_followed_email_idx
  on public.feed_user_follows (lower(followed_email), created_at desc);
create index if not exists feed_user_follows_follower_email_idx
  on public.feed_user_follows (lower(follower_email), created_at desc);

alter table public.feed_user_follows enable row level security;
