-- Instagram-style 24h stories. A story's expires_at is set at insert time
-- so the API can filter with a single "expires_at > now()" check without a
-- separate cleanup job; expired rows are simply never returned. A periodic
-- cleanup can be added later to reclaim storage, but isn't required for
-- correctness.
create table if not exists public.stories (
  id bigint generated by default as identity primary key,
  author_email text not null,
  media_url text not null,
  media_type text not null default 'image' check (media_type in ('image', 'video')),
  caption text,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '24 hours')
);

create index if not exists stories_expires_at_idx on public.stories (expires_at);
create index if not exists stories_author_email_idx on public.stories (lower(author_email));

-- Per-viewer "seen" state, tracked server-side (unlike notification read
-- state, which is local-only) since stories are inherently shared/social
-- and a member's seen state should follow them across devices.
create table if not exists public.story_views (
  story_id bigint not null references public.stories(id) on delete cascade,
  viewer_email text not null,
  viewed_at timestamptz not null default now(),
  primary key (story_id, viewer_email)
);

create index if not exists story_views_viewer_email_idx on public.story_views (lower(viewer_email));
