-- Keep the push notification token store reproducible in source control.
-- This migration is already applied to the production Supabase project.
create table if not exists public.push_tokens (
  id bigint generated by default as identity primary key,
  user_email text not null,
  token text not null unique,
  platform text not null default 'android',
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists push_tokens_user_email_idx
  on public.push_tokens (lower(user_email));

create index if not exists push_tokens_updated_at_idx
  on public.push_tokens (updated_at desc);
