CREATE TABLE IF NOT EXISTS public.bookmark_collections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_email TEXT NOT NULL,
  name TEXT NOT NULL CHECK (char_length(name) BETWEEN 1 AND 40),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS bookmark_collections_user_name_idx
  ON public.bookmark_collections (LOWER(user_email), LOWER(name));
CREATE INDEX IF NOT EXISTS bookmark_collections_user_idx
  ON public.bookmark_collections (LOWER(user_email), created_at);

CREATE TABLE IF NOT EXISTS public.bookmark_collection_items (
  collection_id BIGINT NOT NULL
    REFERENCES public.bookmark_collections(id) ON DELETE CASCADE,
  user_email TEXT NOT NULL,
  item_kind TEXT NOT NULL CHECK (item_kind IN ('post', 'sermon')),
  item_id BIGINT NOT NULL CHECK (item_id > 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (collection_id, item_kind, item_id)
);

CREATE INDEX IF NOT EXISTS bookmark_collection_items_user_idx
  ON public.bookmark_collection_items (LOWER(user_email), collection_id);

ALTER TABLE public.bookmark_collections ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bookmark_collection_items ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE public.bookmark_collections IS
  'Per-account bookmark collections, managed through the authenticated Cloudflare Worker.';
COMMENT ON TABLE public.bookmark_collection_items IS
  'Saved feed items assigned to account-owned bookmark collections.';
