create table if not exists public.message_conversations (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.message_participants (
  conversation_id bigint not null references public.message_conversations(id) on delete cascade,
  user_email text not null,
  last_read_at timestamptz,
  created_at timestamptz not null default now(),
  primary key (conversation_id, user_email)
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null references public.message_conversations(id) on delete cascade,
  sender_email text not null,
  body text not null check (char_length(body) between 1 and 2000),
  created_at timestamptz not null default now()
);

create unique index if not exists message_conversations_pair_idx
  on public.message_participants (conversation_id, lower(user_email));
create index if not exists message_participants_user_idx on public.message_participants (lower(user_email), conversation_id);
create index if not exists messages_conversation_created_idx on public.messages (conversation_id, created_at desc);

create or replace function public.touch_message_conversation()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  update public.message_conversations set updated_at = now() where id = new.conversation_id;
  return new;
end;
$$;

drop trigger if exists messages_touch_conversation on public.messages;
create trigger messages_touch_conversation after insert on public.messages
for each row execute function public.touch_message_conversation();

alter table public.message_conversations enable row level security;
alter table public.message_participants enable row level security;
alter table public.messages enable row level security;

grant select, insert, update on public.message_conversations to authenticated;
grant select, insert, update on public.message_participants to authenticated;
grant select, insert on public.messages to authenticated;

create policy "participants can read conversations" on public.message_conversations
for select to authenticated using (exists (select 1 from public.message_participants p where p.conversation_id = id and lower(p.user_email) = lower(auth.jwt()->>'email')));
create policy "participants can create conversations" on public.message_conversations
for insert to authenticated with check (true);
create policy "participants can read memberships" on public.message_participants
for select to authenticated using (lower(user_email) = lower(auth.jwt()->>'email'));
create policy "users can add themselves to conversations" on public.message_participants
for insert to authenticated with check (lower(user_email) = lower(auth.jwt()->>'email'));
create policy "users can update own membership" on public.message_participants
for update to authenticated using (lower(user_email) = lower(auth.jwt()->>'email')) with check (lower(user_email) = lower(auth.jwt()->>'email'));
create policy "participants can read messages" on public.messages
for select to authenticated using (exists (select 1 from public.message_participants p where p.conversation_id = conversation_id and lower(p.user_email) = lower(auth.jwt()->>'email')));
create policy "participants can send messages" on public.messages
for insert to authenticated with check (lower(sender_email) = lower(auth.jwt()->>'email') and exists (select 1 from public.message_participants p where p.conversation_id = conversation_id and lower(p.user_email) = lower(auth.jwt()->>'email')));

alter publication supabase_realtime add table public.messages;
