create table if not exists public.communities (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null check (char_length(name) between 2 and 80),
  description text not null default '' check (char_length(description) <= 500),
  category text not null default 'General' check (char_length(category) between 2 and 40),
  icon_url text not null default '',
  banner_url text not null default '',
  created_by text not null,
  created_at timestamptz not null default now()
);

create index if not exists communities_category_idx on public.communities(category);
create index if not exists communities_created_at_idx on public.communities(created_at desc, id desc);

create table if not exists public.community_members (
  id bigint generated by default as identity primary key,
  community_id bigint not null references public.communities(id) on delete cascade,
  user_email text not null,
  role text not null default 'member' check (role in ('member','moderator','owner')),
  created_at timestamptz not null default now(),
  unique(community_id, user_email)
);

create index if not exists community_members_user_email_idx on public.community_members(lower(user_email));
create index if not exists community_members_community_idx on public.community_members(community_id);

create table if not exists public.community_posts (
  id bigint generated by default as identity primary key,
  community_id bigint not null references public.communities(id) on delete cascade,
  user_email text not null,
  author_name text not null,
  body text not null check (char_length(body) between 1 and 5000),
  created_at timestamptz not null default now()
);

create index if not exists community_posts_community_created_idx on public.community_posts(community_id, created_at desc, id desc);
create index if not exists community_posts_user_email_idx on public.community_posts(lower(user_email));

alter table public.communities enable row level security;
alter table public.community_members enable row level security;
alter table public.community_posts enable row level security;

insert into public.communities (slug,name,description,category,created_by)
values
  ('creators','Creators','Share ideas, projects, feedback and the work you are building.','Creativity','system'),
  ('entrepreneurs','Entrepreneurs','Business ideas, lessons, opportunities and conversations for builders.','Business','system'),
  ('university-students','University Students','Study life, careers, campus conversations and finding your people.','Education','system'),
  ('music-culture','Music & Culture','Artists, listeners and curious people talking about music and culture.','Culture','system'),
  ('faith-life','Faith & Life','Open conversations about faith, purpose, prayer and everyday life.','Faith','system'),
  ('young-adults','Young Adults','Life, relationships, work, growth and everything in between.','Life','system'),
  ('technology','Technology','AI, coding, products, startups and the future of technology.','Technology','system'),
  ('books-ideas','Books & Ideas','Talk about books, learning, big ideas and what you are discovering.','Learning','system')
on conflict (slug) do nothing;
