create table if not exists public.feed_posts (
  id bigint generated by default as identity primary key,
  user_email text not null,
  author_name text not null,
  type text not null default 'post' check (type in ('post', 'reel')),
  title text not null,
  body text not null default '',
  image_url text not null default '',
  youtube_url text not null default '',
  created_at timestamptz not null default now()
);

create index if not exists feed_posts_created_at_idx on public.feed_posts(created_at desc, id desc);
create index if not exists feed_posts_user_email_idx on public.feed_posts(lower(user_email));
alter table public.feed_posts enable row level security;

create table if not exists public.feed_post_likes (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.feed_posts(id) on delete cascade,
  user_email text not null,
  created_at timestamptz not null default now(),
  unique(post_id, user_email)
);
create index if not exists feed_post_likes_post_id_idx on public.feed_post_likes(post_id);
alter table public.feed_post_likes enable row level security;

create table if not exists public.feed_post_saves (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.feed_posts(id) on delete cascade,
  user_email text not null,
  created_at timestamptz not null default now(),
  unique(post_id, user_email)
);
create index if not exists feed_post_saves_post_id_idx on public.feed_post_saves(post_id);
alter table public.feed_post_saves enable row level security;

create table if not exists public.feed_post_comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.feed_posts(id) on delete cascade,
  user_email text not null,
  author_name text not null,
  body text not null check(char_length(body) between 1 and 1000),
  created_at timestamptz not null default now()
);
create index if not exists feed_post_comments_post_id_created_at_idx on public.feed_post_comments(post_id, created_at desc);
alter table public.feed_post_comments enable row level security;
