-- Reports against Feed content (both user posts and sermon-sourced items).
-- Kept as a single table keyed by the same prefixed id the client already
-- uses everywhere else in the Feed ("p:123" / "s:45") rather than two
-- separate tables per content type, since moderation doesn't need to join
-- against post-specific columns the way likes/saves/comments do.
create table if not exists public.feed_content_reports (
  id bigint generated by default as identity primary key,
  feed_item_id text not null,
  reporter_email text not null,
  reason text not null,
  detail text,
  status text not null default 'open' check (status in ('open', 'dismissed')),
  created_at timestamptz not null default now(),
  unique (feed_item_id, reporter_email)
);

create index if not exists feed_content_reports_status_idx
  on public.feed_content_reports (status, created_at desc);
